### ISSUE TITLE
feathersjs unprocessable agents, spells, etc. on startup

### ISSUE THREAD

**Issue by technobaboo** [Oneirocom/Magick#1217]
### Magick version

e770e15a4e4453a80bb8526cd55ccd15a107afe6 as well as current production build

### System information

Arch Linux

### Issue description

```
USING LOCAL RETE
USING LOCAL RETE
Connecting to redis pubsub
Connecting to redis pubsub
Subscribed to the agent* channel. Listening for updates.
[13:06:03.510] INFO (agent/2047476): Initializing feathers app...
[13:06:03.515] INFO (agent/2047476): SETTING UP REDIS
[13:06:03.984] INFO (agent/2047476): Feathers app initialized
[13:06:03.984] INFO (agent/2047476): Initializing agent...
[13:06:03.984] INFO (agent/2047476): Loading plugins...
[13:06:03.985] INFO (agent/2047476): Plugins loaded: 'GithubPlugin, DiscordPlugin, TwitterPlugin, RestPlugin, LoopPlugin, TaskPlugin, GoogleAIPlugin, OpenAIPlugin, SearchPlugin, BlueskyPlugin, elevenlabsPlugin, databasePlugin, anthropicPlugin'
[13:06:03.985] INFO (agent/2047476): Agent initialized.
file server started on port: 65530
Subscribed to the agent* channel. Listening for updates.
[13:06:03.750] INFO (server/2047477): Initializing feathers app...
[13:06:03.754] INFO (server/2047477): SETTING UP REDIS
[13:06:04.496] INFO (server/2047477): Feathers app initialized
[13:06:04.497] INFO (server/2047477): loaded plugins on server 'GithubPlugin, DiscordPlugin, TwitterPlugin, RestPlugin, LoopPlugin, TaskPlugin, GoogleAIPlugin, OpenAIPlugin, SearchPlugin, BlueskyPlugin, elevenlabsPlugin, databasePlugin, anthropicPlugin'
[13:06:04.508] INFO (server/2047477): Server started on port 3030
Unprocessable: select "agents".* from "agents" where "enabled" = $1 limit $2 - relation "agents" does not exist
    at errorHandler (/run/media/nova/MEDIA/AI/Magick/node_modules/@feathersjs/knex/src/error-handler.ts:85:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AgentService._find (/run/media/nova/MEDIA/AI/Magick/node_modules/@feathersjs/knex/src/adapter.ts:188:46)
    at AgentService.<anonymous> (/run/media/nova/MEDIA/AI/Magick/node_modules/@feathersjs/schema/src/hooks/resolve.ts:97:5)
    at AgentService.<anonymous> (/run/media/nova/MEDIA/AI/Magick/node_modules/@feathersjs/schema/src/hooks/resolve.ts:97:5)
    at AgentService.<anonymous> (/run/media/nova/MEDIA/AI/Magick/node_modules/@feathersjs/schema/src/hooks/resolve.ts:150:5)
    at AgentService.logError (/run/media/nova/MEDIA/AI/Magick/dist/apps/agent/webpack:/packages/core/server/src/hooks/index.ts:12:5)
    at AgentManager.updateAgents (/run/media/nova/MEDIA/AI/Magick/dist/apps/agent/webpack:/packages/agents/src/lib/AgentManager.ts:106:7)
    at Timeout._onTimeout (/run/media/nova/MEDIA/AI/Magick/dist/apps/agent/webpack:/packages/agents/src/lib/AgentManager.ts:43:9)



/run/media/nova/MEDIA/AI/Magick/node_modules/@feathersjs/knex/src/error-handler.ts:85
        feathersError = new errors.Unprocessable(message)
                        ^
Unprocessable: select "agents".* from "agents" where "enabled" = $1 limit $2 - relation "agents" does not exist
    at errorHandler (/run/media/nova/MEDIA/AI/Magick/node_modules/@feathersjs/knex/src/error-handler.ts:85:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AgentService._find (/run/media/nova/MEDIA/AI/Magick/node_modules/@feathersjs/knex/src/adapter.ts:188:46)
    at AgentService.<anonymous> (/run/media/nova/MEDIA/AI/Magick/node_modules/@feathersjs/schema/src/hooks/resolve.ts:97:5)
    at AgentService.<anonymous> (/run/media/nova/MEDIA/AI/Magick/node_modules/@feathersjs/schema/src/hooks/resolve.ts:97:5)
    at AgentService.<anonymous> (/run/media/nova/MEDIA/AI/Magick/node_modules/@feathersjs/schema/src/hooks/resolve.ts:150:5)
    at AgentService.logError (/run/media/nova/MEDIA/AI/Magick/dist/apps/agent/webpack:/packages/core/server/src/hooks/index.ts:12:5)
    at AgentManager.updateAgents (/run/media/nova/MEDIA/AI/Magick/dist/apps/agent/webpack:/packages/agents/src/lib/AgentManager.ts:106:7)
    at Timeout._onTimeout (/run/media/nova/MEDIA/AI/Magick/dist/apps/agent/webpack:/packages/agents/src/lib/AgentManager.ts:43:9)


>  NX  Process exited with code 1, waiting for changes to restart...
```

the web UI will start but i can't access the agents, spells, avatar, etc. tabs because they load infinitely.

### Steps to reproduce

just do npm run dev for the first time, it's definitely a case of "doesn't work on my machine" but still

### Minimal reproduction project

tested with a fully up to date arch machine as of the time of this posting

**Comment by coffeeorgreentea** [comment]
you need to run migrations:
npm run migrate
