### ISSUE TITLE
Spellhandler breaks on hot reload

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#210]
When code is hot reloaded on server, spellhandler throws this:

error: Error: No spell provided to load
    at SpellManager.load (/Users/shawwalters/MagickML/dist/apps/server/webpack:/packages/engine/src/lib/spellManager/SpellManager.ts:77:23)
    at SpellRunnerService.get (/Users/shawwalters/MagickML/dist/apps/server/webpack:/@magickml/server/src/services/spell-runner/spell-runner.class.ts:57:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SpellRunnerService.logError (/Users/shawwalters/MagickML/dist/apps/server/webpack:/@magickml/server/src/hooks/log-error.ts:7:5)
    at runMethod (/Users/shawwalters/MagickML/node_modules/@feathersjs/transport-commons/src/socket/utils.ts:118:38)
CONNECTION ESTABLISHED
error: Error: No spell provided to load
    at SpellManager.load (/Users/shawwalters/MagickML/dist/apps/server/webpack:/packages/engine/src/lib/spellManager/SpellManager.ts:77:23)
    at SpellRunnerService.get (/Users/shawwalters/MagickML/dist/apps/server/webpack:/@magickml/server/src/services/spell-runner/spell-runner.class.ts:57:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SpellRunnerService.logError (/Users/shawwalters/MagickML/dist/apps/server/webpack:/@magickml/server/src/hooks/log-error.ts:7:5)

**Comment by michaelsharpe** [comment]
I will look into this one too.  I thought I had fixed this one.

**Comment by mrmetaverse** [comment]
evaluate this sprint
