### ISSUE TITLE
error: BadRequest: Graph would be cleared.  Aborting.

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#277]
Often times i will get weird requests. They are harmless but we should handle the root cause.

error: BadRequest: Graph would be cleared.  Aborting.
    at SpellService.saveDiff (/Users/shawwalters/MagickML/dist/apps/server/webpack:/packages/server-core/src/services/spells/spells.class.ts:42:13)
    at SpellService.<anonymous> (/Users/shawwalters/MagickML/node_modules/@feathersjs/schema/src/hooks/resolve.ts:105:7)
    at SpellService.<anonymous> (/Users/shawwalters/MagickML/node_modules/@feathersjs/schema/src/hooks/resolve.ts:105:7)
    at SpellService.<anonymous> (/Users/shawwalters/MagickML/node_modules/@feathersjs/schema/src/hooks/resolve.ts:133:7)
    at SpellService.logError (/Users/shawwalters/MagickML/dist/apps/server/webpack:/packages/server-core/src/hooks/index.ts:7:5)
    at runMethod (/Users/shawwalters/MagickML/node_modules/@feathersjs/transport-commons/src/socket/utils.ts:118:38)
error: Error: No triggered node found
    at SpellRunner.runComponent (/Users/shawwalters/MagickML/dist/apps/server/webpack:/packages/engine/src/lib/spellManager/SpellRunner.ts:236:31)
    at SpellManager.run (/Users/shawwalters/MagickML/dist/apps/server/webpack:/packages/engine/src/lib/spellManager/SpellManager.ts:96:34)
    at SpellRunnerService.create (/Users/shawwalters/MagickML/dist/apps/server/webpack:/packages/server-core/src/services/spell-runner/spell-runner.class.ts:90:39)

**Comment by michaelsharpe** [comment]
Yeah. That's the error that it won't save because it would wipe your graph clean. It was a stop gap for that weird effect if reloading the spell and having it clear all the work.

**Comment by lalalune** [comment]
Is this still happening?
