### ISSUE TITLE
Is null or undefined throws an error 

### ISSUE THREAD

**Issue by Knar33** [Oneirocom/Magick#804]
### Magick version

5e219fb

### System information

Ubuntu 22.04.1, firefox

### Issue description

When passing in an undefined variable into the Is null or undefined node, it throws an error about the input being undefined. It should instead gracefully handle this case and return true.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/4692561/236650327-82f66865-94ec-450e-b6ae-fcb8e4e611aa.png)

Recreate this graph and send any input through the playtest. Channel should be undefined so it should return true.

**Comment by Knar33** [comment]
Actually, it throws this error even if you pass in something with a value (like the event destructure content)

**Comment by Knar33** [comment]
ERROR RUNNING SPELL TypeError: Cannot read properties of undefined (reading '0')
    at IsNullOrUndefined.worker (/home/knar/Documents/Github/Magick/dist/apps/server/webpack:/packages/core/shared/src/nodes/flow/IsNullOrUndefined.ts:49:34)
    at IsNullOrUndefined.component.worker (/home/knar/Documents/Github/Magick/dist/apps/server/webpack:/packages/core/shared/src/plugins/consolePlugin/index.ts:53:37)
    at IsNullOrUndefined.component.worker (/home/knar/Documents/Github/Magick/dist/apps/server/webpack:/packages/core/shared/src/plugins/socketPlugin/index.ts:53:41)
    at Task.taskCaller [as worker] (/home/knar/Documents/Github/Magick/dist/apps/server/webpack:/packages/core/shared/src/plugins/taskPlugin/index.ts:66:41)
    at Task.run (/home/knar/Documents/Github/Magick/dist/apps/server/webpack:/packages/core/shared/src/plugins/taskPlugin/task.ts:221:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /home/knar/Documents/Github/Magick/dist/apps/server/webpack:/packages/core/shared/src/plugins/taskPlugin/task.ts:236:22
    at async Promise.all (index 0)
    at Task.run (/home/knar/Documents/Github/Magick/dist/apps/server/webpack:/packages/core/shared/src/plugins/taskPlugin/task.ts:231:9)
    at /home/knar/Documents/Github/Magick/dist/apps/server/webpack:/packages/core/shared/src/plugins/taskPlugin/task.ts:236:22

**Comment by lalalune** [comment]
This is fixed now, needed for ELIZA so I got it working.
