### ISSUE TITLE
Event destructure does not output rawData

### ISSUE THREAD

**Issue by Knar33** [Oneirocom/Magick#808]
### Magick version

c7c1e91

### System information

Ubuntu 22.04.1, firefox

### Issue description

![image](https://user-images.githubusercontent.com/4692561/236702175-bfaf5e70-457d-4c85-9294-be17362f4c09.png)

When trying to output the content of the rawData node, I get an error:

ERROR RUNNING SPELL TypeError: Cannot read properties of undefined (reading '0')
    at ModuleManager.workerOutputs (/home/knar/Documents/Github/Magick/dist/apps/server/webpack:/packages/core/shared/src/plugins/modulePlugin/module-manager.ts:184:48)
    at Output.component.worker (/home/knar/Documents/Github/Magick/dist/apps/server/webpack:/packages/core/shared/src/plugins/modulePlugin/index.ts:253:39)
    at Output.component.worker (/home/knar/Documents/Github/Magick/dist/apps/server/webpack:/packages/core/shared/src/plugins/socketPlugin/index.ts:53:41)
    at Task.taskCaller [as worker] (/home/knar/Documents/Github/Magick/dist/apps/server/webpack:/packages/core/shared/src/plugins/taskPlugin/index.ts:66:41)
    at Task.run (/home/knar/Documents/Github/Magick/dist/apps/server/webpack:/packages/core/shared/src/plugins/taskPlugin/task.ts:221:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /home/knar/Documents/Github/Magick/dist/apps/server/webpack:/packages/core/shared/src/plugins/taskPlugin/task.ts:236:22
    at async Promise.all (index 0)
    at Task.run (/home/knar/Documents/Github/Magick/dist/apps/server/webpack:/packages/core/shared/src/plugins/taskPlugin/task.ts:231:9)
    at /home/knar/Documents/Github/Magick/dist/apps/server/webpack:/packages/core/shared/src/plugins/taskPlugin/task.ts:236:22

### Steps to reproduce

Create the graph above and try to execute a playtest input.

**Comment by Knar33** [comment]
This is a duplicate of the more detailed issue #888
