### ISSUE TITLE
`npm run dev` issues

### ISSUE THREAD

**Issue by fire** [Oneirocom/Magick#819]
### Magick version

7c2d78a3d55c62c53d495b63489ed02065798a9b

### System information

Windows 11, Firefox

### Issue description

Error messages.

```
[plugin:vite:import-analysis] Failed to resolve import "./plugins" from "apps\client\src\main.tsx". Does the file exist?

C:/Users/ernes/Documents/Magick/apps/client/src/main.tsx:10:20

3  |  import { MagickIDE } from "@magickml/editor";
4  |  import { DEFAULT_PROJECT_ID, API_ROOT_URL, TRUSTED_PARENT_URL } from "@magickml/core";
5  |  import plugins from "./plugins";
   |                       ^
6  |  console.log("plugins", plugins);
7  |  if (window === window.parent) {

    at formatError (file:///C:/Users/ernes/Documents/Magick/node_modules/vite/dist/node/chunks/dep-d305c21f.js:43190:46)
    at TransformContext.error (file:///C:/Users/ernes/Documents/Magick/node_modules/vite/dist/node/chunks/dep-d305c21f.js:43186:19)
    at normalizeUrl (file:///C:/Users/ernes/Documents/Magick/node_modules/vite/dist/node/chunks/dep-d305c21f.js:41455:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransformContext.transform (file:///C:/Users/ernes/Documents/Magick/node_modules/vite/dist/node/chunks/dep-d305c21f.js:41589:47)
    at async Object.transform (file:///C:/Users/ernes/Documents/Magick/node_modules/vite/dist/node/chunks/dep-d305c21f.js:43464:30)
    at async loadAndTransform (file:///C:/Users/ernes/Documents/Magick/node_modules/vite/dist/node/chunks/dep-d305c21f.js:41182:29

Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.
```

### Steps to reproduce

```
git clone https://github.com/Oneirocom/Magick magick
cd magick
scoop install npm
npm install
npm run dev
# Open browser
```

### Minimal reproduction project

Git clone the magick repository.

**Comment by fire** [comment]
As far as I know the original issues are gone.
